/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/advisor/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Advisor */
        post: operations["analyze_advisor_api_v1_advisor_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Health */
        get: operations["api_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Item */
        post: operations["parse_item_api_v1_items_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionAnalysisDto */
        ActionAnalysisDto: {
            /** Action Id */
            action_id: string;
            /** Advisor Candidate Status */
            advisor_candidate_status?: string | null;
            /** Applicability */
            applicability: string;
            /**
             * Applicability Reasons
             * @default []
             */
            applicability_reasons: string[];
            /** Display Name */
            display_name: string;
            expected_value?: components["schemas"]["ExpectedValueSummaryDto"] | null;
            /**
             * Failed Preconditions
             * @default []
             */
            failed_preconditions: string[];
            material_cost: components["schemas"]["MaterialCostDto"];
            /**
             * Missing Requirements
             * @default []
             */
            missing_requirements: components["schemas"]["MissingRequirementDto"][];
            /**
             * Outcome Count
             * @default 0
             */
            outcome_count: number;
            /**
             * Outcome Ids
             * @default []
             */
            outcome_ids: string[];
            /** Outcome Space Completeness */
            outcome_space_completeness?: string | null;
            probability?: components["schemas"]["ProbabilitySummaryDto"] | null;
            /** Probability Completeness */
            probability_completeness?: string | null;
            /**
             * Required Materials
             * @default []
             */
            required_materials: components["schemas"]["MaterialRequirementDto"][];
            scenario?: components["schemas"]["ScenarioSummaryDto"] | null;
            /**
             * Unknown Preconditions
             * @default []
             */
            unknown_preconditions: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** AdvisorAnalyzeRequestDto */
        AdvisorAnalyzeRequestDto: {
            /** Affix Capacity Dataset Version */
            affix_capacity_dataset_version: string;
            /** As Of */
            as_of?: string | null;
            bankroll?: components["schemas"]["EconomicValueDto"] | null;
            /** Clipboard Text */
            clipboard_text: string;
            /** Crafting Dataset Version */
            crafting_dataset_version: string;
            current_valuation_evidence?: components["schemas"]["ManualValuationEvidenceDto"] | null;
            /** Empirical Probability Dataset Version */
            empirical_probability_dataset_version?: string | null;
            game_context?: components["schemas"]["GameContextDto"] | null;
            /** Game Data Dataset Version */
            game_data_dataset_version: string;
            /** League */
            league: string;
            /**
             * Outcome Valuation Evidence
             * @default []
             */
            outcome_valuation_evidence: components["schemas"]["OutcomeManualValuationEvidenceDto"][];
            /** Risk Profile */
            risk_profile?: string | null;
        };
        /** AdvisorAnalyzeResponseDto */
        AdvisorAnalyzeResponseDto: {
            /**
             * Actions
             * @default []
             */
            actions: components["schemas"]["ActionAnalysisDto"][];
            affix_state?: components["schemas"]["AffixStateDto"] | null;
            /** Analysis Id */
            analysis_id: string;
            context: components["schemas"]["AdvisorContextDto"];
            decision?: components["schemas"]["AdvisorDecisionDto"] | null;
            enrichment_summary?: components["schemas"]["EnrichmentSummaryDto"] | null;
            item?: components["schemas"]["ItemSummaryDto"] | null;
            /**
             * Missing Requirements
             * @default []
             */
            missing_requirements: components["schemas"]["MissingRequirementDto"][];
            /**
             * Provenance
             * @default []
             */
            provenance: {
                [key: string]: unknown;
            }[];
            risk_adjusted_decision?: components["schemas"]["RiskAdjustedDecisionDto"] | null;
            /** Status */
            status: string;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** AdvisorContextDto */
        AdvisorContextDto: {
            /** Affix Capacity Dataset Version */
            affix_capacity_dataset_version: string;
            /** As Of */
            as_of?: string | null;
            /** Crafting Dataset Version */
            crafting_dataset_version: string;
            /**
             * Economy Snapshot Ids
             * @default []
             */
            economy_snapshot_ids: string[];
            /** Empirical Probability Dataset Version */
            empirical_probability_dataset_version?: string | null;
            /** Game Data Dataset Version */
            game_data_dataset_version: string;
            /** League */
            league: string;
        };
        /** AdvisorDecisionDto */
        AdvisorDecisionDto: {
            /** Algorithm Version */
            algorithm_version?: string | null;
            /** Decision Type */
            decision_type: string;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Selected Candidate Id */
            selected_candidate_id?: string | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** AffixStateDto */
        AffixStateDto: {
            /** Observed Prefix Count */
            observed_prefix_count?: number | null;
            /** Observed Suffix Count */
            observed_suffix_count?: number | null;
            /** Open Prefix Count */
            open_prefix_count?: number | null;
            /** Open Suffix Count */
            open_suffix_count?: number | null;
            /** Prefix Capacity */
            prefix_capacity?: number | null;
            /** Suffix Capacity */
            suffix_capacity?: number | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** ApiErrorDto */
        ApiErrorDto: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: string;
            } | null;
            /** Message */
            message: string;
            /**
             * Recoverable
             * @default true
             */
            recoverable: boolean;
            /**
             * Reliable No Result
             * @default false
             */
            reliable_no_result: boolean;
        };
        /** EconomicValueDto */
        EconomicValueDto: {
            /**
             * Amount
             * @description Decimal amount encoded as a string to avoid binary float corruption.
             */
            amount: string;
            /**
             * Unit
             * @default EXALTED_ECONOMIC_UNIT
             */
            unit: string;
        };
        /** EnrichmentSummaryDto */
        EnrichmentSummaryDto: {
            /**
             * Ambiguous Modifier Count
             * @default 0
             */
            ambiguous_modifier_count: number;
            /** Enrichment Id */
            enrichment_id?: string | null;
            /** Resolved Base Id */
            resolved_base_id?: string | null;
            /**
             * Resolved Modifier Count
             * @default 0
             */
            resolved_modifier_count: number;
            /** Snapshot Id */
            snapshot_id?: string | null;
            /**
             * Unresolved Modifier Count
             * @default 0
             */
            unresolved_modifier_count: number;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** ExpectedValueSummaryDto */
        ExpectedValueSummaryDto: {
            /** Algorithm Version */
            algorithm_version?: string | null;
            /** Available */
            available: boolean;
            craft_cost?: components["schemas"]["EconomicValueDto"] | null;
            current_item_value?: components["schemas"]["EconomicValueDto"] | null;
            expected_gain_vs_sell_now?: components["schemas"]["EconomicValueDto"] | null;
            gross_expected_outcome_value?: components["schemas"]["EconomicValueDto"] | null;
            net_expected_value?: components["schemas"]["EconomicValueDto"] | null;
            /** Roi On Craft Cost */
            roi_on_craft_cost?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Unavailable Reasons
             * @default []
             */
            unavailable_reasons: string[];
        };
        /** GameContextDto */
        GameContextDto: {
            /**
             * Game
             * @default Path of Exile 2
             */
            game: string;
            /** Game Version */
            game_version?: string | null;
            /** League */
            league?: string | null;
            /** Locale */
            locale?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Environment */
            environment: string;
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ItemSummaryDto */
        ItemSummaryDto: {
            /** Base Type */
            base_type?: string | null;
            /**
             * Corruption Enhancements
             * @default []
             */
            corruption_enhancements: components["schemas"]["ModifierDto"][];
            /**
             * Implicit Modifiers
             * @default []
             */
            implicit_modifiers: components["schemas"]["ModifierDto"][];
            /** Item Class */
            item_class?: string | null;
            /** Item Level */
            item_level?: number | null;
            /** Item Name */
            item_name?: string | null;
            /**
             * Prefixes
             * @default []
             */
            prefixes: components["schemas"]["ModifierDto"][];
            /** Rarity */
            rarity?: string | null;
            /** Required Level */
            required_level?: number | null;
            /**
             * Special States
             * @default []
             */
            special_states: string[];
            /**
             * Suffixes
             * @default []
             */
            suffixes: components["schemas"]["ModifierDto"][];
            /**
             * Unparsed Lines
             * @default []
             */
            unparsed_lines: string[];
        };
        /** ManualListingObservationDto */
        ManualListingObservationDto: {
            /**
             * Amount
             * @description Decimal listing amount encoded as string.
             */
            amount: string;
            /** Currency Asset Id */
            currency_asset_id: string;
            /** External Listing Id */
            external_listing_id?: string | null;
            /** Item Summary */
            item_summary?: string | null;
            /** Notes */
            notes?: string | null;
            /** Observed At */
            observed_at?: string | null;
        };
        /** ManualValuationEvidenceDto */
        ManualValuationEvidenceDto: {
            /** Notes */
            notes?: string | null;
            /**
             * Observations
             * @default []
             */
            observations: components["schemas"]["ManualListingObservationDto"][];
            /**
             * Strategy
             * @default STRICT
             */
            strategy: string;
        };
        /** MaterialCostDto */
        MaterialCostDto: {
            /** Complete */
            complete: boolean;
            /** Freshness */
            freshness: string;
            /**
             * Lines
             * @default []
             */
            lines: {
                [key: string]: unknown;
            }[];
            total?: components["schemas"]["EconomicValueDto"] | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** MaterialRequirementDto */
        MaterialRequirementDto: {
            /** Asset Id */
            asset_id: string;
            /** Quantity */
            quantity: string;
        };
        /** MissingRequirementDto */
        MissingRequirementDto: {
            /** Action Id */
            action_id?: string | null;
            /**
             * Blocks
             * @default []
             */
            blocks: string[];
            /** Reason */
            reason: string;
            /** Type */
            type: string;
        };
        /** ModifierDto */
        ModifierDto: {
            /** Affix Type */
            affix_type?: string | null;
            /** Canonical Id */
            canonical_id?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Origin */
            origin?: string | null;
            /** Raw Text */
            raw_text: string;
            /** Resolution Status */
            resolution_status?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Tier */
            tier?: string | null;
        };
        /** OutcomeManualValuationEvidenceDto */
        OutcomeManualValuationEvidenceDto: {
            evidence: components["schemas"]["ManualValuationEvidenceDto"];
            /** Outcome Id */
            outcome_id: string;
        };
        /** OutcomeProbabilitySummaryDto */
        OutcomeProbabilitySummaryDto: {
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["ProbabilityEvidenceSummaryDto"][];
            /** Outcome Id */
            outcome_id: string;
            /** Probability */
            probability?: string | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** ParseItemRequestDto */
        ParseItemRequestDto: {
            /**
             * Game
             * @default Path of Exile 2
             */
            game: string;
            /** Game Version */
            game_version?: string | null;
            /** League */
            league?: string | null;
            /** Locale */
            locale?: string | null;
            /** Raw Clipboard Text */
            raw_clipboard_text: string;
        };
        /** ParseItemResponseDto */
        ParseItemResponseDto: {
            /** Detected Format */
            detected_format: string;
            error?: components["schemas"]["ApiErrorDto"] | null;
            /** Item */
            item?: {
                [key: string]: unknown;
            } | null;
            /**
             * Unparsed Sections
             * @default []
             */
            unparsed_sections: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** ProbabilityEvidenceSummaryDto */
        ProbabilityEvidenceSummaryDto: {
            /** Evidence Dataset Version */
            evidence_dataset_version?: string | null;
            /** Evidence Id */
            evidence_id: string;
            /** Methodology */
            methodology?: string | null;
            /** Outcome Id */
            outcome_id?: string | null;
            /** Probability */
            probability?: string | null;
            /** Probability Type */
            probability_type: string;
            /** Sample Size */
            sample_size?: number | null;
            uncertainty_interval?: components["schemas"]["ProbabilityIntervalDto"] | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** ProbabilityIntervalDto */
        ProbabilityIntervalDto: {
            /** Lower */
            lower: string;
            /** Upper */
            upper: string;
        };
        /** ProbabilitySummaryDto */
        ProbabilitySummaryDto: {
            /** Completeness */
            completeness: string;
            /**
             * Dataset Versions
             * @default []
             */
            dataset_versions: string[];
            /**
             * Known Outcome Count
             * @default 0
             */
            known_outcome_count: number;
            /** Methodology Summary */
            methodology_summary?: string | null;
            /**
             * Outcome Count
             * @default 0
             */
            outcome_count: number;
            /**
             * Outcome Probabilities
             * @default []
             */
            outcome_probabilities: components["schemas"]["OutcomeProbabilitySummaryDto"][];
            /** Source Outcome Set Id */
            source_outcome_set_id: string;
            /** Total Known Probability Mass */
            total_known_probability_mass?: string | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** RiskAdjustedDecisionDto */
        RiskAdjustedDecisionDto: {
            /** Changed By Policy */
            changed_by_policy: boolean;
            /** Decision Type */
            decision_type: string;
            /** Raw Winner Candidate Id */
            raw_winner_candidate_id?: string | null;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Risk Policy Version */
            risk_policy_version?: string | null;
            /** Selected Candidate Id */
            selected_candidate_id?: string | null;
            /**
             * Triggered Rules
             * @default []
             */
            triggered_rules: string[];
        };
        /** ScenarioSummaryDto */
        ScenarioSummaryDto: {
            best_valuated_outcome?: components["schemas"]["EconomicValueDto"] | null;
            downside_relative_to_current?: components["schemas"]["EconomicValueDto"] | null;
            median_valuated_outcome?: components["schemas"]["EconomicValueDto"] | null;
            /**
             * Outcome Count
             * @default 0
             */
            outcome_count: number;
            /** Readiness */
            readiness?: string | null;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /**
             * Unvalued Outcome Count
             * @default 0
             */
            unvalued_outcome_count: number;
            upside_relative_to_current?: components["schemas"]["EconomicValueDto"] | null;
            /** Valuation Completeness */
            valuation_completeness?: string | null;
            /**
             * Valued Outcome Count
             * @default 0
             */
            valued_outcome_count: number;
            worst_valuated_outcome?: components["schemas"]["EconomicValueDto"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_advisor_api_v1_advisor_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvisorAnalyzeRequestDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorAnalyzeResponseDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    parse_item_api_v1_items_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseItemRequestDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseItemResponseDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
